server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: openapi-backend
  profiles:
    active: dev
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    timeout: 2592000 # 30 天过期

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #mybatis-plus自动打开驼峰映射，mybatis则自动关闭
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1 #被删除
      logic-not-delete-value: 0 #正常
# 日志配置
logging:
  level:
    com:
      weng:
        springbootinit:
          mapper: debug
          service: debug
          controller: debug
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.weng.openapibackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

